# Generated by Django 6.0.2 on 2026-03-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipn_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pesapal Configuration',
                'verbose_name_plural': 'Pesapal Configuration',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='iso_country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, help_text='Pesapal order tracking ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SellerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='trendsync.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relations', to='trendsync.seller')),
            ],
            options={
                'unique_together': {('buyer', 'seller')},
            },
        ),
    ]
