# Generated by Django 6.0.2 on 2026-03-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0003_sellerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProductBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_bookmarks', to='trendsync.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_products', to='trendsync.seller')),
            ],
            options={
                'unique_together': {('product', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='SellerProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_likes', to='trendsync.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to='trendsync.seller')),
            ],
            options={
                'unique_together': {('product', 'seller')},
            },
        ),
    ]
