# Generated by Django 6.0.2 on 2026-03-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0003_sellerrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerRating',
        ),
    ]
