# Generated by Django 6.0.2 on 2026-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0004_sellerproductbookmark_sellerproductlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerproductlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sellerproductlike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellerproductlike',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SellerProductBookmark',
        ),
        migrations.DeleteModel(
            name='SellerProductLike',
        ),
    ]
