# Generated by Django 6.0.2 on 2026-03-14 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0005_alter_sellerproductlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='trust',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
