# Generated by Django 6.0.2 on 2026-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0006_alter_seller_trust'),
    ]

    operations = [
        migrations.CreateModel(
            name='DusuPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DusuPay Configuration',
                'verbose_name_plural': 'DusuPay Configuration',
            },
        ),
        migrations.DeleteModel(
            name='PesapalConfig',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pesapal_tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='dusupay_internal_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dusupay_merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
