# Generated by Django 6.0.2 on 2026-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0007_dusupayconfig_delete_pesapalconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='seller',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='location_type',
            field=models.CharField(blank=True, choices=[('static', 'Static Seller'), ('dynamic', 'Dynamic Seller')], max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('card', 'Card Payment'), ('mobile_money', 'Mobile Money')], max_length=20),
        ),
    ]
