# Generated by Django 6.0.2 on 2026-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0008_seller_bank_account_seller_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickdeal',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='quickdeal',
            name='priority',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
