# Generated by Django 6.0.2 on 2026-06-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0010_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fraud', 'Fraud / Scam'), ('fake_product', 'Fake / Counterfeit Product'), ('harassment', 'Harassment / Abuse'), ('spam', 'Spam / Misleading'), ('wrong_category', 'Wrong Category'), ('price_manipulation', 'Price Manipulation'), ('intellectual_property', 'Intellectual Property Violation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, help_text='Additional evidence or details')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='trendsync.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='trendsync.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
