# Generated by Django 6.0.2 on 2026-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendsync', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='recent_searches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
