# trendsync/urls.py - Updated

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .main_views import (
    ProductViewSet,
    WishlistViewSet,
    SellerViewSet,
    CategoryViewSet,
    get_locations,
    rate_seller,
    CartView,
    merge_cart,
    category_list,
    LikedProductsView,
    toggle_product_like,
    check_product_like,
    get_cart_items,
    add_to_cart,
    remove_from_cart,
    update_cart_item,
    clear_cart,
    get_quick_deals,
    increment_quickdeal_views,
    SellerProfileView,
    SellerProductListCreateView,
    SellerProductDetailView,
    SellerOrderListView,
    SellerQuickDealListCreateView,
    SellerQuickDealDetailView,
    SellerStatsView,
    get_wishlist,
    add_to_wishlist,
    remove_from_wishlist,
    toggle_wishlist,
    get_order_count,
    create_order_from_cart,
    comment_detail,
    mark_helpful,
    toggle_follow_seller,
    get_simple_notifications,
    mark_simple_notification_read,
    mark_all_simple_notifications_read,
    delete_simple_notification,
    clear_simple_notifications,
    buyer_profile_detail,
    change_email,
    change_password,
    get_orders,
    get_order_detail,
    dusupay_callback,
    update_seller_location,
    get_chat_inbox,
    get_chat_history,
    mark_chat_read,
    test_send_message,
    create_report,
    get_reports,
    get_report_detail,
    update_report_status,
    get_my_reports,
    recent_searches,
    search_products,
    get_filter_options,
)

from .views import (
    google_login,
    google_callback,
    login_view,
    verify_token_view,
    BuyerRegisterView,
    SellerRegisterView,
)

router = DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'wishlist', WishlistViewSet, basename='wishlist')
router.register(r'sellers', SellerViewSet)
router.register(r'categories', CategoryViewSet, basename='category')

urlpatterns = [
    # ===== GOOGLE OAUTH =====
    path('auth/google/', google_login, name='google-login'),
    path('auth/google/callback/', google_callback, name='google-callback'),
    
    # ===== AUTH =====
    path('login/', login_view, name='login'),
    path('verify-token/', verify_token_view, name='verify_token'),
    path('register/buyer/', BuyerRegisterView.as_view(), name='register-buyer'),
    path('register/seller/', SellerRegisterView.as_view(), name='register-seller'),
    
    # ===== LOCATIONS =====
    path('locations/', get_locations, name='get-locations'),
    
    # ===== SEARCH AND FILTERS (NO /api/ prefix - main urls.py adds it) =====
    path('products/search/', search_products, name='search-products'),
    path('products/search', search_products, name='search-products-no-slash'),  # extra
    path('filter-options/', get_filter_options, name='filter-options'),
    path('recent-searches/', recent_searches, name='recent-searches'),
    
    # ===== ROUTER =====
    path('', include(router.urls)),

    # ===== REST OF YOUR URLS =====
    path('sellers/rate/', rate_seller, name='rate-seller'),
    path('cart/', CartView.as_view()),
    path('cart/merge/', merge_cart),
    path('categories/', category_list, name='category_list'),
    path('liked-products/', LikedProductsView.as_view(), name='liked-products'),
    path('products/<int:product_id>/toggle-like/', toggle_product_like, name='toggle-product-like'),
    path('products/<int:product_id>/check-like/', check_product_like, name='check-product-like'),
    path('cart/items/', get_cart_items, name='get-cart-items'),
    path('cart/add/', add_to_cart, name='add-to-cart'),
    path('cart/remove/<int:product_id>/', remove_from_cart, name='remove-from-cart'),
    path('cart/update/<int:product_id>/', update_cart_item, name='update-cart-item'),
    path('cart/clear/', clear_cart, name='clear-cart'),
    path('quick-deals/', get_quick_deals, name='quick-deals'),
    path('quick-deals/<int:deal_id>/view/', increment_quickdeal_views, name='increment-quickdeal-views'),
    path('seller/profile/', SellerProfileView.as_view(), name='seller-profile'),
    path('seller/products/', SellerProductListCreateView.as_view(), name='seller-products'),
    path('seller/products/<int:pk>/', SellerProductDetailView.as_view(), name='seller-product-detail'),
    path('seller/orders/', SellerOrderListView.as_view(), name='seller-orders'),
    path('seller/quick-deals/', SellerQuickDealListCreateView.as_view(), name='seller-quick-deals'),
    path('seller/quick-deals/<int:pk>/', SellerQuickDealDetailView.as_view(), name='seller-quickdeal-detail'),
    path('seller/stats/', SellerStatsView.as_view(), name='seller-stats'),
    path('seller/location/update/', update_seller_location, name='update-seller-location'),
    path('wishlist/', get_wishlist, name='get-wishlist'),
    path('wishlist/add/', add_to_wishlist, name='add-to-wishlist'),
    path('wishlist/remove/<int:product_id>/', remove_from_wishlist, name='remove-from-wishlist'),
    path('wishlist/toggle/<int:product_id>/', toggle_wishlist, name='toggle-wishlist'),
    path('orders/count/', get_order_count, name='order-count'),
    path('orders/create-from-cart/', create_order_from_cart, name='create-order-from-cart'),
    path('comments/<int:comment_id>/', comment_detail, name='comment-detail'),
    path('comments/<int:comment_id>/helpful/', mark_helpful, name='comment-helpful'),
    path('sellers/<int:seller_id>/follow/', toggle_follow_seller, name='toggle-follow-seller'),
    path('simple-notifications/', get_simple_notifications, name='simple-notifications'),
    path('simple-notifications/<int:notification_id>/read/', mark_simple_notification_read, name='simple-notification-read'),
    path('simple-notifications/read-all/', mark_all_simple_notifications_read, name='simple-notifications-read-all'),
    path('simple-notifications/<int:notification_id>/delete/', delete_simple_notification, name='simple-notification-delete'),
    path('simple-notifications/clear-all/', clear_simple_notifications, name='simple-notifications-clear'),
    path('buyer/profile/', buyer_profile_detail, name='buyer-profile-detail'),
    path('change-email/', change_email, name='change-email'),
    path('change-password/', change_password, name='change-password'),
    path('orders/', get_orders, name='get-orders'),
    path('orders/<int:order_id>/', get_order_detail, name='order-detail'),
    path('payments/callback/', dusupay_callback, name='dusupay-callback'),
    path('chat/inbox/', get_chat_inbox, name='chat-inbox'),
    path('chat/<int:user_id>/', get_chat_history, name='chat-history'),
    path('chat/mark-read/<int:user_id>/', mark_chat_read, name='mark-chat-read'),
    path('chat/test-send/', test_send_message, name='test-send-message'),
    path('reports/create/', create_report, name='create-report'),
    path('reports/', get_reports, name='get-reports'),
    path('reports/my/', get_my_reports, name='my-reports'),
    path('reports/<int:report_id>/', get_report_detail, name='report-detail'),
    path('reports/<int:report_id>/update-status/', update_report_status, name='update-report-status'),
]